### ISSUE TITLE
Email Auth에 대한 Table/Entity 설계

### ISSUE THREAD

**Issue by hankyungeun** [KH-Final-Team1/BookFinder_Backend#21]
# Email Auth에 대한 Table/Entity 설계
#### 회원가입, 비민번호 찾기 시 인증 코드를 담아두는 테이블
- auth_id: 이메일 인증id, bigint, primary key
- email: email, varchar(255), unique, not null
- code: 코드번호, int, not null
- create_time: 인증 요청 시간, date, not null

# Issue
- 회원가입 후 비밀번호 찾기 시도 시 email을 unique로 두면 중복 저장 불가
  - 인증 요청 시간이 만료되면 튜플 삭제할 것인가?

**Comment by JinHoooooou** [comment]
- create_time → expiration으로 변경
  - 5분후 만료이기 때문에 Date → LocalDateTime으로 변경
  - 
- email과 auth code를 묶어서 Unique를 두었기 때문에 이메일이 중복 되더라도 auth code가 중복이 아니기 때문에 괜찮을 듯
  - 단, 우연히 email과 auth code 모두 같아지면 ...?
- 현재 RDBMS에서는 expiration 지나도 삭제를 하지 않지만 추후에 NoSQL(Redis 등)으로 변경하면 삭제할 예정
