### ISSUE TITLE
Book Entity 객체 설계

### ISSUE THREAD

**Issue by JinHoooooou** [KH-Final-Team1/BookFinder_Backend#7]
## PR
#8 

## Book에 대한 Table/Entity 설계

- ISBN: 13자리 isbn  → Primary key
- ADDITION_SYMBOL: ISBN 부가기호
- NAME: 도서명
- AUTHORS: 저자명 (여러명일 수 있으므로)
- PUBLISHER: 출판사
- PUBLICATION_YEAR: 출판년도
- PUBLICATION_DATE: 출판일자
- CLASS_NO: 주제분류
- CLASS_NAME: 주제분류명
- DESCRIPTION: 책 소개
- IMAGE_URL: 책 표지 URL

##  Issue
- 초기 데이터를 어떻게 넣을 것인가
  1. 인기 대출 도서 조회 API를 통해 get json list
  2. json list를 sql 파일로 저장
  3. sql파일 실행
- 초기 데이터를 넣을 SQL문에 DESCRIPTION과 PUBLICATION_DATE는 빈 값(Empty)이다.
  - 인기 대출 도서 조회 API에는 DESCRIPTION과 PUBLICATION_DATE가 응답으로 주어지지 않음.
  - 일단은 Empty/Null로 추가

**Comment by hankyungeun** [comment]
## Q.
-----
출판 년도랑 출판 일자 컬럼이 각각 필요한 이유랑 사용 목적이 있을까용?
