### ISSUE TITLE
User에 대한 Table/Entity 설계

### ISSUE THREAD

**Issue by JinHoooooou** [KH-Final-Team1/BookFinder_Backend#9]
# User에 대한 Table/Entity 설계
- user_id: User Id번호, Long, Primary Key, Auto Increment
- email: 이메일, String, not null, unique
- password: 패스워드, String, not null
- phone: 연락처, String
- nickname: 닉네임, String, not null, unique
- address_id: 주소 Id번호, Long, FK (Address)
- status: 상태, String, @Enumerated, (ADMIN, NORMAL, DISABLED, WITHDRAWAL)
  - ADMIN: 관리자
  - NORMAL: 일반 회원
  - DISABLED: 이용정지
  - WITHDRAWAL: 탈퇴  

# Issue
- email을 PK로 하자 → Auto Increment인 User Id컬럼 추가
  - User Id를 1부터 시작하는 Auto Increment(Sequence)로 할지, UUID?를 이용할지 회의 필요
  - 카카오 로그인 API 연동할 것이라면 9자리의 임의의 번호를 사용하는게 나을것같음
- Address 테이블 필요
  - #13 
- 상태를 ADMIN, NORMAL, DISABLED, WITHDRAWAL만 뒀는데 더 필요할지 회의 필요
  - 참고: https://rastalion.me/%ED%9A%8C%EC%9B%90-%EA%B0%80%EC%9E%85-%EB%B0%8F-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84-%EC%9C%84%ED%95%9C-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%84%A4%EA%B3%84/

**Comment by hankyungeun** [comment]
## +
user 테이블에 address의 pk를 담을 컬럼 추가
